# Generated by Django 6.1.1 on 2026-10-10 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_reglas_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='faltante',
            field=models.PositiveIntegerField(default=0, help_text='Unidades que se vendieron aunque no había stock registrado suficiente'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.ubicacion'),
        ),
    ]
