# Generated by Django 6.1.1 on 2026-09-16 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en que aparece el filtro en la página')),
                ('mostrar_como_filtro', models.BooleanField(default=True, help_text='Si está marcado, este atributo aparece como filtro en el catálogo público')),
            ],
            options={
                'verbose_name': 'Atributo (filtro)',
                'verbose_name_plural': 'Atributos (filtros)',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número = aparece primero')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='NeuroMisael Tienda', max_length=100)),
                ('whatsapp_numero', models.CharField(blank=True, help_text="Con código de país, sin '+' ni espacios. Ej: 59171234567", max_length=20)),
                ('mensaje_whatsapp_base', models.CharField(default='Hola, quiero consultar sobre el producto: {producto}', help_text='Usa {producto} donde quieras que aparezca el nombre del producto', max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('texto_bienvenida', models.CharField(blank=True, default='Juguetes y objetos de estimulación impresos en 3D', max_length=250)),
                ('horario_atencion', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, help_text='Aparece en la tarjeta del catálogo', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción completa, en la ficha del producto')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en Bs.', max_digits=10)),
                ('disponible', models.BooleanField(default=True, help_text='Se muestra en el catálogo público')),
                ('destacado', models.BooleanField(default=False, help_text='Se resalta primero en el catálogo')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-destacado', 'orden', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/%Y/%m/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='catalogo.atributo')),
            ],
            options={
                'verbose_name': 'Valor de atributo',
                'verbose_name_plural': 'Valores de atributo',
                'ordering': ['atributo__orden', 'valor'],
                'unique_together': {('atributo', 'valor')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='atributos',
            field=models.ManyToManyField(blank=True, help_text='Ej: Material=PLA, Color=Azul, Edad recomendada=3-5 años', related_name='productos', to='catalogo.valoratributo'),
        ),
    ]
