# Generated by Django 6.1.1 on 2026-09-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: PLA blanco, PETG azul', max_length=80, unique=True)),
                ('costo_por_kg', models.DecimalField(decimal_places=2, help_text='Costo del rollo/kg en Bs.', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Filamento',
                'verbose_name_plural': 'Filamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='horas_uso_anual',
            field=models.PositiveIntegerField(blank=True, help_text='Horas que usas la impresora al año aproximadamente (para repartir el mantenimiento)', null=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='mantenimiento_anual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasto anual estimado en repuestos (boquillas, correas, cama, etc.), en Bs.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='margen_ganancia_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de ganancia deseado sobre el costo (ej. 50 = 50%), usado para el precio sugerido.', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='potencia_impresora_kw',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Consumo real de la impresora en kW mientras imprime (no la potencia máxima de la fuente). Ej: 0.120', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='precio_impresora',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cuánto costó la impresora, en Bs. (para calcular la depreciación por hora)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='precio_kwh',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Precio del kWh según tu factura de luz, en Bs.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='tasa_fallas_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% estimado de piezas que fallan al imprimir (ej. 10 = 10%). Se usa para que las piezas buenas cubran el costo de las que fallan.', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='vida_util_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Horas de vida útil estimadas de la impresora antes de necesitar reparación mayor. Si no sabes, un estimado razonable es 4,000-5,000 horas.', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='horas_impresion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas que tarda en imprimirse esta pieza', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_gramos',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Peso de la pieza impresa, en gramos', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text="Precio real de venta en Bs. (el que ve el cliente). Tú decides el número final; usa el 'precio sugerido' de abajo solo como referencia.", max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='filamento',
            field=models.ForeignKey(blank=True, help_text='Filamento usado, para calcular el costo de material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.filamento'),
        ),
    ]
