# Generated by Django 6.1.1 on 2026-09-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_filamento_configuracionsitio_horas_uso_anual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoratributo',
            name='color_hex',
            field=models.CharField(blank=True, help_text="Solo para valores de color. Código hex (ej: #3B82F6) para mostrar un redondito de ese color en los filtros, en vez del nombre en texto. Para un color variado, escribe la palabra 'multicolor' (se dibuja un redondito estilo arcoíris). Si no sabes el código exacto, déjalo vacío: se mostrará el nombre en texto, que es más honesto que un color inventado.", max_length=20),
        ),
    ]
