# Generated by Django 6.1.1 on 2026-09-17 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_valoratributo_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='nombre_tienda',
            field=models.CharField(default='Misael Toys', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='texto_bienvenida',
            field=models.CharField(blank=True, default='Jugar · Explorar · Aprender — juguetes y objetos de estimulación impresos en 3D', max_length=250),
        ),
        migrations.CreateModel(
            name='LikeProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitante_id', models.CharField(db_index=True, max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Me gusta',
                'verbose_name_plural': 'Me gusta',
                'unique_together': {('producto', 'visitante_id')},
            },
        ),
    ]
