# Generated by Django 6.1.1 on 2026-09-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_total_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='texto_bienvenida',
            field=models.CharField(blank=True, default='Jugar · Explorar · Aprender — juguetes sensoriales impresos en 3D', max_length=250),
        ),
    ]
