# Generated by Django 6.1.1 on 2026-09-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_configuracionsitio_texto_bienvenida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='recomendado_por_terapeutas',
            field=models.BooleanField(default=False, help_text="Muestra el sello 'Recomendado por terapeutas' en la tarjeta y en la ficha del producto. Actívalo solo en productos que tu equipo de terapeutas realmente evaluó: el sello pierde valor si aparece en todo.", verbose_name='Recomendado por terapeutas'),
        ),
    ]
