# Generated by Django 6.1.1 on 2026-10-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_producto_recomendado_por_terapeutas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='detalle_envios',
            field=models.CharField(blank=True, help_text="Una línea extra con condiciones reales, ej: 'Coordinamos costo y empresa de transporte por WhatsApp'. Escribe solo lo que realmente ofreces.", max_length=250, verbose_name='Detalle de envíos (opcional)'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='envios_nacionales',
            field=models.BooleanField(default=True, help_text='Si está marcado, se muestra el aviso de envíos en la portada, en cada producto y en el pie de página.', verbose_name="Mostrar 'Envíos a nivel nacional'"),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='texto_envios',
            field=models.CharField(default='Envíos a todo el país', help_text="Es el texto principal del aviso. Ej: 'Envíos a todo el país'", max_length=120, verbose_name='Mensaje corto de envíos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='alto_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='largo_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Lado más largo de la pieza ya armada, en centímetros', max_digits=6, null=True, verbose_name='Largo (cm)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='medidas_nota',
            field=models.CharField(blank=True, help_text="Para sets o piezas variadas. Ej: 'Anillos de 4 a 8 cm de diámetro' o 'Set de 6 piezas'", max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='referencia_tamano',
            field=models.CharField(blank=True, help_text="Comparación cotidiana para que el cliente se imagine el tamaño. Ej: 'Cabe en la palma de una mano adulta' o 'Similar a una pelota de tenis'", max_length=120),
        ),
    ]
