# Generated by Django 6.1.1 on 2026-10-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_medidas_y_envios'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono de contacto 2 (opcional)'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='whatsapp_etiqueta',
            field=models.CharField(blank=True, help_text='Aparece en la burbuja de WhatsApp. Ej: Ventas, Consultas, Rosa', max_length=40, verbose_name='Nombre del WhatsApp 1 (opcional)'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='whatsapp_etiqueta_2',
            field=models.CharField(blank=True, help_text='Ej: Ventas, Consultas, Rosa', max_length=40, verbose_name='Nombre del WhatsApp 2 (opcional)'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='whatsapp_numero_2',
            field=models.CharField(blank=True, help_text='Segundo número. Mismo formato: 59171234567', max_length=20, verbose_name='WhatsApp 2 (opcional)'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono de contacto 1'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text="Con código de país, sin '+' ni espacios. Ej: 59171234567", max_length=20, verbose_name='WhatsApp 1'),
        ),
    ]
