# Generated by Django 6.1.1 on 2026-10-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_contactos_dobles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='telefono',
            field=models.CharField(blank=True, help_text='Es el número que se muestra en el sitio, las cotizaciones y los recibos', max_length=30, verbose_name='Teléfono de contacto 1'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='telefono_2',
            field=models.CharField(blank=True, help_text='Segundo número que se muestra junto al primero', max_length=30, verbose_name='Teléfono de contacto 2 (opcional)'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Solo se usa en los botones que abren WhatsApp. Con código de país. Ej: 59171234567', max_length=20, verbose_name='WhatsApp 1 (solo para los botones)'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='whatsapp_numero_2',
            field=models.CharField(blank=True, help_text='Segundo número para los botones de WhatsApp. Mismo formato: 59171234567', max_length=20, verbose_name='WhatsApp 2 (opcional, solo para los botones)'),
        ),
    ]
